import type { Metadata } from "next";
import "../styles/globals.css";
import "@radix-ui/themes/styles.css";
import Navbar from "@/components/ui/Navbar";
import Footer from "@/components/ui/Footer";
import StoreProvider from "./StoreProvider";
import { Theme } from "@radix-ui/themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <StoreProvider>
        <body className="dark:bg-slate-950">
          <div className="flex items-center justify-center font-poppins">
            <div className="h-screen max-w-[70rem] w-[90%]">
              <div>
                <Navbar />
              </div>
              <div>
                <Theme>{children}</Theme>
              </div>
              <div>
                <Footer />
              </div>
            </div>
          </div>
        </body>
      </StoreProvider>
    </html>
  );
}
